---
title: Gendered words over time in the Times Data Archive
---


We can start by loading the libraries we will be using for data analysis. 

```{r loadLibraries}
suppressPackageStartupMessages(library(yaml))
suppressPackageStartupMessages(library(dplyr))
suppressPackageStartupMessages(library(ggplot2))
suppressPackageStartupMessages(library(MASS))
suppressPackageStartupMessages(library(data.table))
suppressPackageStartupMessages(library(magrittr))
```


Now we need to load in our data file and change the structure from YAML
to something that we can more easily manipulate.

```{r loadData}
data = yaml.load_file("result.yml")
counts = lapply(names(data), function(year){
  lapply(data[[year]], function(pair) {
    data.frame(year=as.numeric(year), word=pair[[1]], count=as.numeric(pair[[2]]))
  }) %>% rbindlist
}) %>% rbindlist
```

```{r simplePlot,fig.height=50,fig.width=10}
ggplot(counts, aes(x=year,y=count +1)) + 
  geom_point() +
  geom_line() +
  scale_y_log10() +
  facet_wrap(~word, ncol=4) + 
  theme(axis.text.x = element_text(angle = 90, hjust = 1))
```